#!/usr/bin/env bash
set -eux

OPTS=$(getopt -o '' --long data-dir:,snapshot-spec:,sbom-path: -- "$@")
eval set -- "$OPTS"

data_dir=""
snapshot_spec=""
sbom_path=""

while true; do
    case "$1" in
        --data-dir)
            data_dir="$2"
            shift 2
            ;;
        --snapshot-spec)
            snapshot_spec="$2"
            shift 2
            ;;
        --sbom-path)
            sbom_path="$2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "Invalid option: $1" >&2
            exit 1
            ;;
    esac
done

if [[ -z "$data_dir" || \
      -z "$snapshot_spec" || \
      -z "$sbom_path"
]]; then
    echo "Error: Both --data-dir and --snapshot-spec are required" >&2
    exit 1
fi

output_path="${data_dir}/${sbom_path}"
mkdir -p "$output_path"

# todo: add --verification-key optionally, once work on release-time
# SBOM in registry is done
mobster --verbose augment \
  --output "$output_path" \
  oci-image \
  --snapshot "${data_dir}/${snapshot_spec}"
