#!/usr/bin/env bash
set -eux

OPTS=$(getopt -o '' --long data-dir:,snapshot-spec:,release-data:,sbom-path: -- "$@")
eval set -- "$OPTS"

data_dir=""
snapshot_spec=""
release_data=""
sbom_path=""

while true; do
    case "$1" in
        --data-dir)
            data_dir="$2"
            shift 2
            ;;
        --snapshot-spec)
            snapshot_spec="$2"
            shift 2
            ;;
        --release-data)
            release_data="$2"
            shift 2
            ;;
        --sbom-path)
            sbom_path="$2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "Invalid option: $1" >&2
            exit 1
            ;;
    esac
done

if [[ -z "$data_dir" || \
      -z "$snapshot_spec" || \
      -z "$release_data" || \
      -z "$sbom_path"
]]; then
    echo "Error: missing required args" >&2
    exit 1
fi

output_dir="${data_dir}/${sbom_path}/"
mkdir -p "$output_dir"

mobster --verbose generate \
  --output ${output_dir}/sbom.json \
  product \
  --snapshot "${data_dir}/${snapshot_spec}" \
  --release-data "${data_dir}/${release_data}"
