FROM registry.access.redhat.com/ubi9/ubi:latest

ARG TRUSTD_VERSION=0.2.1

USER root

RUN useradd --uid 1000 tpa && \
    dnf install -y tar gzip && \
    dnf clean all

USER tpa

WORKDIR /app

RUN curl -L https://github.com/trustification/trustify/releases/download/v${TRUSTD_VERSION}/trustd-pm-${TRUSTD_VERSION}-x86_64-unknown-linux-gnu.tar.gz \
    -o trustd-pm.tar.gz && \
    tar -xzf trustd-pm.tar.gz && \
    rm trustd-pm.tar.gz

WORKDIR /app/trustd-pm-${TRUSTD_VERSION}-x86_64-unknown-linux-gnu/

ENV AUTH_DISABLED=true
ENV HTTP_SERVER_BIND_ADDR=::

CMD ["./trustd-pm"]
