"""Syft integration for scanning OCI images and generating SBOMs."""

import json
from typing import Any

from mobster.utils import run_async_subprocess


async def scan_image(image_pullspec: str) -> dict[str, Any]:
    """
    Scan an OCI image using Syft and return the SBOM as a dictionary.

    Args:
        image_pullspec (str): The OCI image pull specification.

    Returns:
        dict: The SBOM generated by Syft in dictionary format.
    """

    cmd = [
        "syft",
        "scan",
        image_pullspec,
        "-o",
        "spdx-json@2.3",
    ]

    return_code, stdout, stderr = await run_async_subprocess(cmd, retry_times=3)

    if return_code != 0:
        raise RuntimeError(
            f"Syft scan failed with exit code {return_code}. Stderr: {stderr.decode()}"
        )

    sbom_dict = json.loads(stdout.decode())
    return sbom_dict  # type: ignore[no-any-return]
