"""Syft integration for scanning OCI images and generating SBOMs."""

import json
from typing import Any

from mobster.utils import run_async_subprocess

# Formats accepted by `syft scan -o`
SPDX_JSON = "spdx-json@2.3"
CYCLONEDX_JSON = "cyclonedx-json"


async def scan_image(
    image_pullspec: str,
    output_format: str = SPDX_JSON,
) -> dict[str, Any]:
    """
    Scan an OCI image using Syft and return the SBOM as a dictionary.

    Args:
        image_pullspec: The OCI image pull specification.
        output_format: Syft output format (default: SPDX JSON 2.3).

    Returns:
        The SBOM generated by Syft as a dictionary.
    """

    cmd = [
        "syft",
        "scan",
        image_pullspec,
        "-o",
        output_format,
    ]

    return_code, stdout, stderr = await run_async_subprocess(cmd, retry_times=3)

    if return_code != 0:
        raise RuntimeError(
            f"Syft scan failed with exit code {return_code}. Stderr: {stderr.decode()}"
        )

    sbom_dict = json.loads(stdout.decode())
    return sbom_dict  # type: ignore[no-any-return]
