---
apiVersion: tekton.dev/v1
kind: Task

metadata:
  name: create-product-sbom-ta
  labels:
    app.kubernetes.io/version: "0.2.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: sbom

spec:
  description: >-
    Create product-level SBOM from release-time information and upload it to
    Atlas and S3.
  params:
    - name: ociStorage
      description: The OCI repository where the Trusted Artifacts are stored.
      type: string
      default: "empty"

    - name: ociArtifactExpiresAfter
      description: Expiration date for the trusted artifacts created in the
        OCI repository. An empty string means the artifacts do not expire.
      type: string
      default: "1d"

    - name: trustedArtifactsDebug
      description: Flag to enable debug logging in trusted artifacts. Set to a non-empty string to enable.
      type: string
      default: ""

    - name: orasOptions
      description: oras options to pass to Trusted Artifacts calls
      type: string
      default: ""

    - name: sourceDataArtifact
      type: string
      description: Location of trusted artifacts to be used to populate data directory
      default: ""

    - name: dataDir
      description: The location where data will be stored
      type: string
      default: /var/workdir/release

    - name: taskGitUrl
      type: string
      description: The url to the git repo where the trusted artifact stepactions to be used are stored

    - name: taskGitRevision
      type: string
      description: The revision in the taskGitUrl repo to be used for trusted artifact stepactions

    - name: snapshotSpec
      type: string
      description: Path to the mapped snapshot spec in the dataDir.

    - name: releaseData
      type: string
      description: Path to the merged data file from collect-data in the dataDir.

    - name: atlasSecretName
      type: string
      description: >
        The name of the K8s secret containing the 'sso_account' and 'sso_token'
        keys used for Atlas OIDC authentication.

    - name: retryAWSSecretName
      type: string
      description: >
        The name of the K8s secret containing the 'atlas-aws-access-key-id' and
        'atlas-aws-secret-access-key' keys used for AWS S3 access.

    - name: retryS3Bucket
      type: string
      default: ""
      description: >
        The name of the S3 bucket used to store data for the retry mechanism.

    - name: atlasApiUrl
      type: string
      default: ""
      description: URL of the Atlas API host.

    - name: ssoTokenUrl
      description: URL of the SSO token issuer.
      default: ""
      type: string

    - name: concurrency
      description: |
        Maximum number of concurrent operations to perform. Higher limit will
        speed up execution for larger snapshots, but will have higher memory
        requirements.
      default: "8"
      type: string

    - name: resultsDirPath
      type: string
      description: Path to directory in the dataDir to store JSON task results to.

  results:
    - description: Produced trusted data artifact
      name: sourceDataArtifact
      type: string

  volumes:
    - name: workdir
      emptyDir: {}

  stepTemplate:
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
    env:
      - name: IMAGE_EXPIRES_AFTER
        value: $(params.ociArtifactExpiresAfter)
      - name: "ORAS_OPTIONS"
        value: "$(params.orasOptions)"
      - name: "DEBUG"
        value: "$(params.trustedArtifactsDebug)"

  steps:
    - name: use-trusted-artifact
      ref:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: stepactions/use-trusted-artifact/use-trusted-artifact.yaml
      params:
        - name: workDir
          value: $(params.dataDir)
        - name: sourceDataArtifact
          value: $(params.sourceDataArtifact)

    - name: process-product-sbom
      image: quay.io/konflux-ci/mobster@sha256:d46f25aed27c9ffc737709866ddb2594d3c2c80319529d86520a0bf745596af1
      computeResources:
        limits:
          memory: 1Gi
        requests:
          memory: 1Gi
          cpu: 350m
      env:
        - name: MOBSTER_TPA_SSO_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: $(params.atlasSecretName)
              key: sso_account
              optional: true
        - name: MOBSTER_TPA_SSO_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.atlasSecretName)
              key: sso_token
              optional: true
        - name: MOBSTER_TPA_SSO_TOKEN_URL
          value: $(params.ssoTokenUrl)
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: $(params.retryAWSSecretName)
              key: atlas-aws-access-key-id
              optional: true
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: $(params.retryAWSSecretName)
              key: atlas-aws-secret-access-key
              optional: true
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
      script: |
        #!/usr/bin/env bash
        set -eux
        # This is a little fragile, ideally it would be just a param. It's here
        # for consistency with other tasks in release-service-catalog. The
        # script below will verify that the release_id has the correct format.
        release_id=$(dirname "$(params.snapshotSpec)")

        process_product_sbom \
          --data-dir "$(params.dataDir)" \
          --snapshot-spec "$(params.snapshotSpec)" \
          --release-data "$(params.releaseData)" \
          --atlas-api-url "$(params.atlasApiUrl)" \
          --retry-s3-bucket "$(params.retryS3Bucket)" \
          --release-id "$release_id" \
          --concurrency "$(params.concurrency)" \
          --result-dir "$(params.resultsDirPath)"

    - name: create-trusted-artifact
      ref:
        resolver: "git"
        params:
          - name: url
            value: "$(params.taskGitUrl)"
          - name: revision
            value: "$(params.taskGitRevision)"
          - name: pathInRepo
            value: stepactions/create-trusted-artifact/create-trusted-artifact.yaml
      params:
        - name: ociStorage
          value: $(params.ociStorage)
        - name: workDir
          value: $(params.dataDir)
        - name: sourceDataArtifact
          value: $(results.sourceDataArtifact.path)
